[build]
  command = "npm install --prefix frontend && npm run build --prefix frontend"

# Redirect with a 200 for api
[[redirects]]
  from = "/api/*"
  to = "https://mern-chatapp-cvds.onrender.com//api/:splat"
  status = 200